create schema ds0;
create schema ds1;
# --==========================
create table if not exists ds0.`ORDER-0`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds0.`ORDER-1`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds0.`ORDER-2`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds0.`ORDER-3`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds1.`ORDER-0`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds1.`ORDER-1`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds1.`ORDER-2`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists ds1.`ORDER-3`( order_id bigint not null auto_increment, buyer_id bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (order_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
# --==========================
create table if not exists ds0.`ORDER-DETAIL-0`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds0.`ORDER-DETAIL-1`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds0.`ORDER-DETAIL-2`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds0.`ORDER-DETAIL-3`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds1.`ORDER-DETAIL-0`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds1.`ORDER-DETAIL-1`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds1.`ORDER-DETAIL-2`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists ds1.`ORDER-DETAIL-3`( o_detail_id bigint not null auto_increment, order_id bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (o_detail_id)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
# --==========================
