create schema JAVA003_ds_0;
create schema JAVA003_ds_1;
--==========================
create table if not exists JAVA003_ds_0.`ORDER_0`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_0.`ORDER_1`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_0.`ORDER_2`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_0.`ORDER_3`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_1.`ORDER_0`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_1.`ORDER_1`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_1.`ORDER_2`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
create table if not exists JAVA003_ds_1.`ORDER_3`( ORDER_ID bigint not null auto_increment, BUYER_ID bigint not null, DETAIL_ID bigint not null, PAYMENT bigint not null, STATUS varchar(10) not null, ORDER_TIME bigint not null, primary key (ORDER_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單清單';
--==========================
create table if not exists JAVA003_ds_0.`ORDER_DETAIL_0`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_0.`ORDER_DETAIL_1`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_0.`ORDER_DETAIL_2`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_0.`ORDER_DETAIL_3`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_1.`ORDER_DETAIL_0`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_1.`ORDER_DETAIL_1`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_1.`ORDER_DETAIL_2`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
create table if not exists JAVA003_ds_1.`ORDER_DETAIL_3`( O_DETAIL_ID bigint not null auto_increment, ORDER_ID bigint not null, PRODUCT_ID bigint not null, AMOUNT int not null, PAYMENT bigint not null, primary key (O_DETAIL_ID)) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '訂單詳細資料';
--==========================
