schemaName: sharding_db

dataSourceCommon:
  username: root
  password:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 5
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  ds_0:
   url: jdbc:mysql://127.0.0.1:33016/JAVA003_ds_0?serverTimezone=UTC&useSSL=false
  ds_1:
   url: jdbc:mysql://127.0.0.1:33016/JAVA003_ds_1?serverTimezone=UTC&useSSL=false

rules:
  - !SHARDING
   tables:
     ORDER:
       actualDataNodes: ds_${0..1}.ORDER_${0..3}
       tableStrategy:
         standard:
           shardingColumn: order_id
           shardingAlgorithmName: order_inline
       keyGenerateStrategy:
         column: order_id
         keyGeneratorName: snowflake
     ORDER_DETAIL:
       actualDataNodes: ds_${0..1}.ORDER_DETAIL_${0..3}
       tableStrategy:
         standard:
           shardingColumn: order_id
           shardingAlgorithmName: order_detail_inline
       keyGenerateStrategy:
         column: o_detail_id
         keyGeneratorName: snowflake
       databaseStrategy:
         standard:
           shardingColumn: order_id
           shardingAlgorithmName: database_order_detail_inline
   bindingTables:
     - ORDER,ORDER_DETAIL
   defaultDatabaseStrategy:
     standard:
       shardingColumn: buyer_id
       shardingAlgorithmName: database_inline
   defaultTableStrategy:
     none:

   shardingAlgorithms:
     database_inline:
       type: INLINE
       props:
         algorithm-expression: ds_${buyer_id % 2}
     database_order_detail_inline:
       type: INLINE
       props:
         algorithm-expression: ds_${order_id % 2}
     order_inline:
       type: INLINE
       props:
         algorithm-expression: ORDER_${order_id % 4}
     order_detail_inline:
       type: INLINE
       props:
         algorithm-expression: ORDER_DETAIL_${order_id % 4}
   keyGenerators:
     snowflake:
       type: SNOWFLAKE
       props:
         worker-id: 123
